build_from:
  aarch64: ghcr.io/hassio-addons/base:17.2.1
  amd64:   ghcr.io/hassio-addons/base:17.2.1
  armv7:   ghcr.io/hassio-addons/base:17.2.1
  i386:    ghcr.io/hassio-addons/base:17.2.1
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: MinIO"
  org.opencontainers.image.description: "MinIO high-performance object storage"
  org.opencontainers.image.source: "https://github.com/kalw/hassio-addons"
  org.opencontainers.image.licenses: "MIT"
args:
  MINIO_VERSION: "RELEASE.2024-03-21T23-13-43Z"