---
name: "MinIO"
version: "dev"
slug: "minio"
description: "MinIO high-performance object storage"
url: "https://github.com/kalw/hassio-addons/tree/master/minio"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
map:
  - share:rw
  - ssl
ports:
  9000/tcp: [PORT:api_port]
  9001/tcp: [PORT:console_port]
ports_description:
  9000/tcp: "API port"
  9001/tcp: "Console port"
panel_icon: "mdi:database"
panel_title: "MinIO"
ingress: true
options:
  ssl_certificate: null
  ssl_key: null
  data_path: "/share/minio"
  username: "admin"
  password: null
schema:
  ssl_certificate: "str?"
  ssl_key: "str?"
  data_path: "str"
  username: "str"
  password: "str"
