---
name: "MinIO"
version: "1.0.0"
slug: "minio"
description: "MinIO high-performance object storage"
url: "https://github.com/kalw/hassio-addons/tree/master/minio"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
map:
  - share:rw
  - ssl
ports:
  9000/tcp: 9000
  9001/tcp: 9001
ports_description:
  9000/tcp: "API port"
  9001/tcp: "Web console port"
webui: "http://[HOST]:[PORT:9001]"
panel_icon: "mdi:database"
panel_title: "MinIO"
ingress: true
ingress_port: 9001
options:
  ssl_certificate: null
  ssl_key: null
  data_path: "/share/minio"
  console_port: 9001
  api_port: 9000
  username: "admin"
  password: null
schema:
  ssl_certificate: "str?"
  ssl_key: "str?"
  data_path: "str"
  console_port: "port?"
  api_port: "port?"
  username: "str"
  password: "str"
